### ISSUE TITLE
Pluralisation for languages with multiple plurals is wrong

### ISSUE THREAD

**Issue by queicherius** [i18next/i18next-gettext-converter#49] opened 2016-06-20 23:11 UTC
Right now, the converter (`po` -> `json`) returns multiple plurals in the wrong format for i18next (e.g. for Czech):

```bash
key_1 # should be key_0
key_3 # should be key_1
key_5 # should be key_2
```

I am guessing that is because i18next changed their format? The numbers are coming from [this file](https://github.com/i18next/i18next-gettext-converter/blob/master/src/plurals.js) and are set [here](https://github.com/i18next/i18next-gettext-converter/blob/master/src/gettextWrapper.js#L446).

**Comment by jamuhl** [comment] 2016-06-21 06:42
correct... @perrin4869 is on a bigger rewrite...so i hope this gets addressed on the way...

**Comment by perrin4869** [comment] 2016-06-21 12:19
actually, I am using i18next for languages like Japanese and Chinese which do not have plurals... so I am not well acquainted with the way plurals are supposed to work. Would appreciate a PR or a rundown of what the problem is here, I can tackle it with the rest no problem

**Comment by jamuhl** [comment] 2016-06-21 12:48
if i get it right from i18next >= v3.x.x the new plural value is the index:

https://github.com/i18next/i18next-gettext-converter/blob/master/src/gettextWrapper.js#L487

should be changed to ` return `_${i}`;`

**Comment by queicherius** [comment] 2016-06-21 19:30
> if i get it right from i18next >= v3.x.x the new plural value is the index:
> should be changed to return_${i};

It's only the index for languages with > 2 plural forms, so it should be something like this:

```js
    getI18nextPluralExtension: function(ext, i) {
      return ext.numbers.length === 2
        ? i === 0 ? '' : '_plural'
        : '_' + i
    }
```

**Comment by perrin4869** [comment] 2016-06-24 03:21
Just pushed the fix. I think I got this right. That being said, I'm not very well acquainted with how plurals work. If it's still not right, I'd appreciate a PR!

**Closed by perrin4869** 2016-06-24 03:21 UTC

**Comment by queicherius** [comment] 2016-06-24 16:13
Just wanted to confirm that everything is working. Thank you for the new release @perrin4869! 🎉

**Comment by perrin4869** [comment] 2016-06-24 16:27
Awesome!!!
